<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cource_model');
        $this->load->model('User_model');
         $this->load->model('User_clas_model');
        $this->load->model('Clas_model');
        $_SESSION['navi'] = 'admin';
    }

    function index()
    {
        
        $data['user_class'] = $this->User_clas_model->get_all_user_class();
        $data['course'] = $this->Cource_model->get_all_cource();
 
        $teacherID = $_SESSION["user"]->account;
        $data['_course'] = $this->Cource_model->get_courses_by_teacherID($teacherID);
        $data['teacher'] = $this->User_model->get_user_by_Permission('GV');
        $data['ST'] = $this->User_model->get_user_by_Permission('HV');
        
        $data['_view'] = 'admin';
        $this->load->view('layouts/main',$data);
    }

    

    function fetch_by_courseID(){
        $courseId=$this->input->post('courseID');
        $sc=$this->Clas_model->get_clas_by_courseID($courseId);//lấy danh sách theo courseId
        print_r($sc);
        if($sc!=""){
            $html="";
            foreach($sc as $key => $obj){
                $html.=" <option value='".($obj['classID'])."'>". ($obj['times'])."</option>";
            }
            print_r($html);//cục html select box
        }
        else{
            echo "<option value=''>không có dữ liệu</option>";
        }
    }

   
    public function student_by_classID(){
        $classId=$this->input->post('id');
        $value=$this->User_clas_model->get_student_by_classID($classId);//lấy danh sách theo yearSchoolId
     
        for ($i=0; $i < count($value); $i++) {
            $new[$i] = new stdClass;
            $new[$i]->id = $i +1;
            $new[$i]->name = $value[$i]['name'];
            $new[$i]->email = $value[$i]['email'];
            $new[$i]->phone = $value[$i]['phone'];
            $new[$i]->result = $value[$i]['result'];
            $new[$i]->action = '
                    <a class="btn btn-success btn-xs btn-raised" href="' . base_url() . 'user/detail_user/' . $value[$i]['account'] . '"  data-toggle="tooltip" data-original-title="Xem thông tin HV"  aria-hidden="true"><i class="material-icons">search</i></a>
                  
                ';
        }

        $new = array('data' => $new);    
        $data = json_encode($new,JSON_UNESCAPED_UNICODE);
        print_r($data);
        return ;

    }

    function listST(){
        $_SESSION['navi'] = 'listST';
        $teacherID = $_SESSION["user"]->account;
        $data['_course'] = $this->Cource_model->get_courses_by_teacherID($teacherID);
        $data['_view'] = 'student/listST';
        $this->load->view('layouts/main',$data);
    }
}
