<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Clas extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Clas_model');
    } 

    /*
     * Listing of class
     */
    function index()
    {
        $data['class'] = $this->Clas_model->get_all_class();
        
        $data['_view'] = 'clas/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new clas
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('courseID','CourseID','required|integer');
		$this->form_validation->set_rules('teacherID','TeacherID','required|max_length[150]');
		$this->form_validation->set_rules('times','Times','required|max_length[250]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'teacherID' => $this->input->post('teacherID'),
				'times' => $this->input->post('times'),
            );
            
            $clas_id = $this->Clas_model->add_clas($params);
            redirect('clas/index');
        }
        else
        {            
            $data['_view'] = 'clas/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a clas
     */
    function edit($classID)
    {   
        // check if the clas exists before trying to edit it
        $data['clas'] = $this->Clas_model->get_clas($classID);
        
        if(isset($data['clas']['classID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('courseID','CourseID','required|integer');
			$this->form_validation->set_rules('teacherID','TeacherID','required|max_length[150]');
			$this->form_validation->set_rules('times','Times','required|max_length[250]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'teacherID' => $this->input->post('teacherID'),
					'times' => $this->input->post('times'),
                );

                $this->Clas_model->update_clas($classID,$params);            
                redirect('clas/index');
            }
            else
            {
                $data['_view'] = 'clas/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The clas you are trying to edit does not exist.');
    } 

    /*
     * Deleting clas
     */
    function remove($classID)
    {
        $clas = $this->Clas_model->get_clas($classID);

        // check if the clas exists before trying to delete it
        if(isset($clas['classID']))
        {
            $this->Clas_model->delete_clas($classID);
            redirect('clas/index');
        }
        else
            show_error('The clas you are trying to delete does not exist.');
    }
    
}
