<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cource extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cource_model');
    } 

    /*
     * Listing of cource
     */
    function index()
    {
        $data['cource'] = $this->Cource_model->get_all_cource();
        
        $data['_view'] = 'cource/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cource
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('author','Author','required');
		$this->form_validation->set_rules('images','Images','required');
		$this->form_validation->set_rules('nameCourse','NameCourse','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nameCourse' => $this->input->post('nameCourse'),
				'view' => $this->input->post('view'),
				'author' => $this->input->post('author'),
				'description' => $this->input->post('description'),
				'images' => $this->input->post('images'),
            );
            
            $cource_id = $this->Cource_model->add_cource($params);
            redirect('cource/index');
        }
        else
        {            
            $data['_view'] = 'cource/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cource
     */
    function edit($course)
    {   
        // check if the cource exists before trying to edit it
        $data['cource'] = $this->Cource_model->get_cource($course);
        
        if(isset($data['cource']['course']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('author','Author','required');
			$this->form_validation->set_rules('images','Images','required');
			$this->form_validation->set_rules('nameCourse','NameCourse','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nameCourse' => $this->input->post('nameCourse'),
					'view' => $this->input->post('view'),
					'author' => $this->input->post('author'),
					'description' => $this->input->post('description'),
					'images' => $this->input->post('images'),
                );

                $this->Cource_model->update_cource($course,$params);            
                redirect('cource/index');
            }
            else
            {
                $data['_view'] = 'cource/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cource you are trying to edit does not exist.');
    } 

    /*
     * Deleting cource
     */
    function remove($course)
    {
        $cource = $this->Cource_model->get_cource($course);

        // check if the cource exists before trying to delete it
        if(isset($cource['course']))
        {
            $this->Cource_model->delete_cource($course);
            redirect('cource/index');
        }
        else
            show_error('The cource you are trying to delete does not exist.');
    }
    
}
