<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cource_model');
        $this->load->model('User_model');
        $_SESSION['navi'] = 'dashboard';
        
    }

    function index()
    {
        $data['_course'] = $this->Cource_model->get_all_cource();
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }

    function detail_course($id){
        // $courseID = $this->input->post('courseID');
        // print_r($courseID);
        $data['_Dcourse'] = $this->Cource_model->get_cource($id);
        if(isset($data['_Dcourse']['courseID'])){

            
        }
        else
            show_error('The user you are trying to finđ does not exist.');
        $this->load->view('detail_course',$data);
    }
}
