<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_uc extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_uc_model');
    } 

    /*
     * Listing of detail_uc
     */
    function index()
    {
        $data['detail_uc'] = $this->Detail_uc_model->get_all_detail_uc();
        
        $data['_view'] = 'detail_uc/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_uc
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('courseID','CourseID','required|max_length[100]');
		$this->form_validation->set_rules('account','Account','required|max_length[100]');
		$this->form_validation->set_rules('status','Status','required|max_length[250]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'account' => $this->input->post('account'),
				'status' => $this->input->post('status'),
            );
            
            $detail_uc_id = $this->Detail_uc_model->add_detail_uc($params);
            redirect('detail_uc/index');
        }
        else
        {            
            $data['_view'] = 'detail_uc/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_uc
     */
    function edit($)
    {   
        // check if the detail_uc exists before trying to edit it
        $data['detail_uc'] = $this->Detail_uc_model->get_detail_uc($);
        
        if(isset($data['detail_uc']['']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('courseID','CourseID','required|max_length[100]');
			$this->form_validation->set_rules('account','Account','required|max_length[100]');
			$this->form_validation->set_rules('status','Status','required|max_length[250]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'account' => $this->input->post('account'),
					'status' => $this->input->post('status'),
                );

                $this->Detail_uc_model->update_detail_uc($,$params);            
                redirect('detail_uc/index');
            }
            else
            {
                $data['_view'] = 'detail_uc/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_uc you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_uc
     */
    function remove($)
    {
        $detail_uc = $this->Detail_uc_model->get_detail_uc($);

        // check if the detail_uc exists before trying to delete it
        if(isset($detail_uc['']))
        {
            $this->Detail_uc_model->delete_detail_uc($);
            redirect('detail_uc/index');
        }
        else
            show_error('The detail_uc you are trying to delete does not exist.');
    }
    
}
