<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_cl extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_cl_model');
    } 

    /*
     * Listing of detail_cl
     */
    function index()
    {
        $data['detail_cl'] = $this->Detail_cl_model->get_all_detail_cl();
        
        $data['_view'] = 'detail_cl/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_cl
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('courseID','CourseID','required');
		$this->form_validation->set_rules('lessonID','LessonID','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'lessonID' => $this->input->post('lessonID'),
            );
            
            $detail_cl_id = $this->Detail_cl_model->add_detail_cl($params);
            redirect('detail_cl/index');
        }
        else
        {            
            $data['_view'] = 'detail_cl/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_cl
     */
    function edit($)
    {   
        // check if the detail_cl exists before trying to edit it
        $data['detail_cl'] = $this->Detail_cl_model->get_detail_cl($);
        
        if(isset($data['detail_cl']['']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('courseID','CourseID','required');
			$this->form_validation->set_rules('lessonID','LessonID','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'lessonID' => $this->input->post('lessonID'),
                );

                $this->Detail_cl_model->update_detail_cl($,$params);            
                redirect('detail_cl/index');
            }
            else
            {
                $data['_view'] = 'detail_cl/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_cl you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_cl
     */
    function remove($)
    {
        $detail_cl = $this->Detail_cl_model->get_detail_cl($);

        // check if the detail_cl exists before trying to delete it
        if(isset($detail_cl['']))
        {
            $this->Detail_cl_model->delete_detail_cl($);
            redirect('detail_cl/index');
        }
        else
            show_error('The detail_cl you are trying to delete does not exist.');
    }
    
}
