<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_lc extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_lc_model');
    } 

    /*
     * Listing of detail_lc
     */
    function index()
    {
        $data['detail_lc'] = $this->Detail_lc_model->get_all_detail_lc();
        
        $data['_view'] = 'detail_lc/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new detail_lc
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('courseID','CourseID','required|integer');
		$this->form_validation->set_rules('lessonID','LessonID','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'courseID' => $this->input->post('courseID'),
				'lessonID' => $this->input->post('lessonID'),
            );
            
            $detail_lc_id = $this->Detail_lc_model->add_detail_lc($params);
            redirect('detail_lc/index');
        }
        else
        {            
            $data['_view'] = 'detail_lc/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a detail_lc
     */
    function edit($)
    {   
        // check if the detail_lc exists before trying to edit it
        $data['detail_lc'] = $this->Detail_lc_model->get_detail_lc($);
        
        if(isset($data['detail_lc']['']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('courseID','CourseID','required|integer');
			$this->form_validation->set_rules('lessonID','LessonID','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'courseID' => $this->input->post('courseID'),
					'lessonID' => $this->input->post('lessonID'),
                );

                $this->Detail_lc_model->update_detail_lc($,$params);            
                redirect('detail_lc/index');
            }
            else
            {
                $data['_view'] = 'detail_lc/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The detail_lc you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail_lc
     */
    function remove($)
    {
        $detail_lc = $this->Detail_lc_model->get_detail_lc($);

        // check if the detail_lc exists before trying to delete it
        if(isset($detail_lc['']))
        {
            $this->Detail_lc_model->delete_detail_lc($);
            redirect('detail_lc/index');
        }
        else
            show_error('The detail_lc you are trying to delete does not exist.');
    }
    
}
