<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Permission extends MY_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Permission_model');
    } 

    /*
     * Listing of permission
     */
    function index()
    {
        $data['permission'] = $this->Permission_model->get_all_permission();
        
        $data['_view'] = 'permission/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new permission
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('namePermission','NamePermission','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'namePermission' => $this->input->post('namePermission'),
            );
            
            $permission_id = $this->Permission_model->add_permission($params);
            redirect('permission/index');
        }
        else
        {            
            $data['_view'] = 'permission/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a permission
     */
    function edit($permissionID)
    {   
        // check if the permission exists before trying to edit it
        $data['permission'] = $this->Permission_model->get_permission($permissionID);
        
        if(isset($data['permission']['permissionID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('namePermission','NamePermission','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'namePermission' => $this->input->post('namePermission'),
                );

                $this->Permission_model->update_permission($permissionID,$params);            
                redirect('permission/index');
            }
            else
            {
                $data['_view'] = 'permission/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The permission you are trying to edit does not exist.');
    } 

    /*
     * Deleting permission
     */
    function remove($permissionID)
    {
        $permission = $this->Permission_model->get_permission($permissionID);

        // check if the permission exists before trying to delete it
        if(isset($permission['permissionID']))
        {
            $this->Permission_model->delete_permission($permissionID);
            redirect('permission/index');
        }
        else
            show_error('The permission you are trying to delete does not exist.');
    }
    
}
