<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_uuc_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_uuc by 
     */
    function get_detail_uuc($)
    {
        return $this->db->get_where('detail_uuc',array(''=>$))->row_array();
    }
        
    /*
     * Get all detail_uuc
     */
    function get_all_detail_uuc()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('detail_uuc')->result_array();
    }
        
    /*
     * function to add new detail_uuc
     */
    function add_detail_uuc($params)
    {
        $this->db->insert('detail_uuc',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_uuc
     */
    function update_detail_uuc($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('detail_uuc',$params);
    }
    
    /*
     * function to delete detail_uuc
     */
    function delete_detail_uuc($)
    {
        return $this->db->delete('detail_uuc',array(''=>$));
    }
}
