<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Clas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get clas by classID
     */
    // function get_clas($classID)
    // {
    //     return $this->db->get_where('class',array('classID'=>$classID))->row_array();
    // }
    function get_clas($classID)
    {
        return $this->db->select("cl.*,c.nameCourse,c.price")->from('class cl')
        ->join('cource c','c.courseID = cl.courseID')
        ->where('cl.classID',$classID)
        ->get() 
        ->row_array();
        // return $this->db->get_where('detail_lc',array('courseID'=>$courseID))->result_array();
    } 
   
    function get_clas_by_courseID($courseID)
    {
        return $this->db->get_where('class',array('courseID'=>$courseID))->result_array();
    }

    function get_class_of_teacherID_by_courseID($account,$courseID){
        return $this->db->select("cl.*")->from('class cl')
        ->join('cource c','c.courseID = cl.courseID')->where(array('cl.teacherID' => $account,'cl.courseID'=>$courseID))
        ->get() 
        ->result_array();
    }
    
    function get_clas_by_teacherID($account)
    {
        return $this->db->get_where('class',array('teacherID'=>$account))->result_array();
    } 

    function get_class_by_teacherID_classID($courseID,$teacherID){
        return $this->db->get_where('class',array('courseID'=>$courseID,'teacherID' =>$teacherID))->row_array();
    }
    function get_teacherID_courseID_by_classID()
    {
        return $this->db->select("cl.*,c.nameCourse")->from('class cl')
        ->join('cource c','c.courseID = cl.courseID')
        ->get() 
        ->result_array();
        // return $this->db->get_where('detail_lc',array('courseID'=>$courseID))->result_array();
    } 
    /*
     * Get all class
     */
    function get_all_class()
    {
        $this->db->order_by('classID', 'desc');
        return $this->db->get('class')->result_array();
    }
        
    /*
     * function to add new clas
     */
    function add_clas($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update clas
     */
    function update_clas($classID,$params)
    {
        $this->db->where('classID',$classID);
        return $this->db->update('class',$params);
    }
    
    /*
     * function to delete clas
     */
    function delete_clas($classID)
    {
        return $this->db->delete('class',array('classID'=>$classID));
    }
}
