<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Clas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get clas by classID
     */
    function get_clas($classID)
    {
        return $this->db->get_where('class',array('classID'=>$classID))->row_array();
    }

    function get_clas_by_courseID($courseID)
    {
        return $this->db->get_where('class',array('courseID'=>$courseID))->result_array();
    }
        
    /*
     * Get all class
     */
    function get_all_class()
    {
        $this->db->order_by('classID', 'desc');
        return $this->db->get('class')->result_array();
    }
        
    /*
     * function to add new clas
     */
    function add_clas($params)
    {
        $this->db->insert('class',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update clas
     */
    function update_clas($classID,$params)
    {
        $this->db->where('classID',$classID);
        return $this->db->update('class',$params);
    }
    
    /*
     * function to delete clas
     */
    function delete_clas($classID)
    {
        return $this->db->delete('class',array('classID'=>$classID));
    }
}
