<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cource_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cource by courseID
     */
    function get_cource($courseID)
    {
        return $this->db->get_where('cource',array('courseID'=>$courseID))->row_array();
    }
        
    /*
     * Get all cource
     */
    function get_all_cource()
    {
        $this->db->order_by('courseID', 'desc');
        return $this->db->get('cource')->result_array();
    }
    
    function get_courses_by_teacherID($teacherID){
        return $this->db->select("c.*")->from('class cl')
        ->join('cource c','c.courseID = cl.courseID')
        ->where('cl.teacherID',$teacherID)
        ->get() 
        ->result_array();
    }
    /*
     * function to add new cource
     */
    function add_cource($params)
    {
        $this->db->insert('cource',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cource
     */
    function update_cource($courseID,$params)
    {
        $this->db->where('courseID',$courseID);
        return $this->db->update('cource',$params);
    }
    
    /*
     * function to delete cource
     */
    function delete_cource($courseID)
    {
        return $this->db->delete('cource',array('courseID'=>$courseID));
    }
}
