<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cource_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cource by course
     */
    function get_cource($course)
    {
        return $this->db->get_where('cource',array('course'=>$course))->row_array();
    }
        
    /*
     * Get all cource
     */
    function get_all_cource()
    {
        $this->db->order_by('course', 'desc');
        return $this->db->get('cource')->result_array();
    }
        
    /*
     * function to add new cource
     */
    function add_cource($params)
    {
        $this->db->insert('cource',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cource
     */
    function update_cource($course,$params)
    {
        $this->db->where('course',$course);
        return $this->db->update('cource',$params);
    }
    
    /*
     * function to delete cource
     */
    function delete_cource($course)
    {
        return $this->db->delete('cource',array('course'=>$course));
    }
}
