<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_cl_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_cl by 
     */
    function get_detail_cl($)
    {
        return $this->db->get_where('detail_cl',array(''=>$))->row_array();
    }
        
    /*
     * Get all detail_cl
     */
    function get_all_detail_cl()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('detail_cl')->result_array();
    }
        
    /*
     * function to add new detail_cl
     */
    function add_detail_cl($params)
    {
        $this->db->insert('detail_cl',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_cl
     */
    function update_detail_cl($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('detail_cl',$params);
    }
    
    /*
     * function to delete detail_cl
     */
    function delete_detail_cl($)
    {
        return $this->db->delete('detail_cl',array(''=>$));
    }
}
