<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_lc_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_lc by 
     */
    function get_detail_lc($id)
    {
        return $this->db->get_where('detail_lc',array('id'=>$id))->row_array();
    }
    function get_detail_lc_by_lessonID($lessonID)
    {
        return $this->db->get_where('detail_lc',array('lessonID'=>$lessonID))->result_array();
    }  
    function get_detail_lc_by_courseID($courseID)
    {
        return $this->db->get_where('detail_lc',array('courseID'=>$courseID))->result_array();
    }  
    /*
     * Get all detail_lc
     */
    function get_all_detail_lc()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('detail_lc')->result_array();
    }
        
    /*
     * function to add new detail_lc
     */
    function add_detail_lc($params)
    {
        $this->db->insert('detail_lc',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_lc
     */
    function update_detail_lc($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('detail_lc',$params);
    }
    
    /*
     * function to delete detail_lc
     */
    function delete_detail_lc($id)
    {
        return $this->db->delete('detail_lc',array('id'=>$id));
    }
}
