<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Type_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get type_user by userTypeID
     */
    function get_type_user($userTypeID)
    {
        return $this->db->get_where('type_user',array('userTypeID'=>$userTypeID))->row_array();
    }
        
    /*
     * Get all type_user
     */
    function get_all_type_user()
    {
        $this->db->order_by('userTypeID', 'desc');
        return $this->db->get('type_user')->result_array();
    }
        
    /*
     * function to add new type_user
     */
    function add_type_user($params)
    {
        $this->db->insert('type_user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update type_user
     */
    function update_type_user($userTypeID,$params)
    {
        $this->db->where('userTypeID',$userTypeID);
        return $this->db->update('type_user',$params);
    }
    
    /*
     * function to delete type_user
     */
    function delete_type_user($userTypeID)
    {
        return $this->db->delete('type_user',array('userTypeID'=>$userTypeID));
    }
}
