<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by account
     */
    function get_user($account)
    {
        return $this->db->get_where('user',array('account'=>$account))->row_array();
    }
    // function get_user_by_promissionID()
    // {
    //     return $this->db->get_where('user',array('permissionID'=>"GV"))->result_array();
    // }  
    function get_permission_by_promissionID($account)
    {
       
        return $this->db->select("u.*, p.namePermission")->from('user u')->join('permission p','p.permissionID = u.permissionID')
        ->where(array('u.account' => $account))
        ->get() 
        ->row_array();
    } 
    function get_author_create_lesson(){
        return $this->db->select("u.account")->from('user u')->or_where_in('u.permissionID', array('GV','AD'))
        ->get() 
        ->result_array();   
    }
    function get_user_by_namePermission()
    {
        
        return $this->db->select("u.*, p.namePermission")->from('user u')->join('permission p','p.permissionID = u.permissionID')
        ->get() 
        ->result_array();
    }  

    function get_user_by_Permission($permissionID)// get list admin, teacher, student
    {
        
        return $this->db->select("u.*, p.namePermission")->from('user u')->join('permission p','p.permissionID = u.permissionID')
        ->where(array('u.permissionID' => $permissionID))
        ->get() 
        ->result_array();
    }
 
    function get_user_by_authorAD()
    {
        return $this->db->get_where('user',array('permissionID'=>'AD'))->result_array();
        // return $this->db->select("u.account")->from('user u')->where('permissionID', 'AD')
        // ->get() 
        // ->result_array();
    } 
    /*
     * Get all user
     */
    function get_all_user()
    {
        $this->db->order_by('account', 'desc');
        return $this->db->get('user')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($account,$params)
    {
        $this->db->where('account',$account);
        return $this->db->update('user',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($account)
    {
        return $this->db->delete('user',array('account'=>$account));
    }
}
