<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detail_uc_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail_uc by 
     */
    function get_detail_uc($)
    {
        return $this->db->get_where('detail_uc',array(''=>$))->row_array();
    }
        
    /*
     * Get all detail_uc
     */
    function get_all_detail_uc()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('detail_uc')->result_array();
    }
        
    /*
     * function to add new detail_uc
     */
    function add_detail_uc($params)
    {
        $this->db->insert('detail_uc',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail_uc
     */
    function update_detail_uc($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('detail_uc',$params);
    }
    
    /*
     * function to delete detail_uc
     */
    function delete_detail_uc($)
    {
        return $this->db->delete('detail_uc',array(''=>$));
    }
}
